name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs_on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          g++ -o output main.cpp
          ./output
